### PR TITLE
Update Xceed.Wpf.AvalonDock.Themes.VS2013.dll from repository.

### PR DESCRIPTION
**Pull request by Kibnet**

### CODE REVIEW

**Comment by EchterAgo** [comment]
If you changed something in the library you should submit a pull request to https://github.com/4ux-nbIx/AvalonDock.Themes.VS2013 so we know what actually changed.

**Comment by Kibnet** [comment]
These changes were introduced by commit [2af8d5b](https://github.com/4ux-nbIx/AvalonDock.Themes.VS2013/commit/2af8d5b3c5f20ab558c8264dd77c2a9554eec18e).

**Comment by Kibnet** [comment]
Pull request [#14](https://github.com/4ux-nbIx/AvalonDock.Themes.VS2013/pull/14) was approved.

**Comment by EchterAgo** [comment]
Sorry, seems like I missed that :+1:

**Comment by EchterAgo** [comment]
@tgjones should we maybe switch to getting this package from NuGet? There aren't really any changes in the Gemini version that are not upstream yet.

**Comment by tgjones** [comment]
> should we maybe switch to getting this package from NuGet?

Sounds good to me.

**Comment by tgjones** [comment]
Superceded by #254.

**Pull request closed without merging**
