### PR TITLE
Add German and Chinese (Simplified) localization to Gemini

### PR DESCRIPTION
**Pull request by EchterAgo**
This handles the inspector and output module as well as the Gemini core.
There were quite a few places where user visible strings were hardcoded
which have been changed to use a resource file. This also adds a
dependency on Gu.Wpf.Localization, which after careful evaluation seems to
be the best fit for Gemini because it is MIT licensed and under active
maintenance. Gu.Wpf.Localization is used to localize the xaml parts of
Gemini.

The settings were enhanced by adding a new combo box to select the active
language, which requires a restart to change. The default is to use the
current system language.

Signed-off-by: Axel Gembe <axel@gembe.net>

### CODE REVIEW

**Comment by EchterAgo** [comment]
Chinese localization is also coming soon

**Comment by EchterAgo** [comment]
Don't merge yet, there is still a problem with the English localization and the samples

**Comment by EchterAgo** [comment]
https://github.com/JohanLarsson/Gu.Localization/issues/11

**Comment by EchterAgo** [comment]
https://github.com/JohanLarsson/Gu.Localization/pull/12

**Comment by EchterAgo** [comment]
Themes: Make setting the theme more robust

Use the themes class name to write into the settings so that the name can
be localized. Also improve the error handling in case the theme can not be
set, restoring the default theme.

Signed-off-by: Axel Gembe <axel@gembe.net>

**Comment by EchterAgo** [comment]
It is working now, can be merged

**Comment by EchterAgo** [comment]
2016-06-20 10_21_39-options

2016-06-20 10_23_08-interactive asia optiremote
2016-06-20 10_22_41-interactive asia optiremote

**Comment by EchterAgo** [comment]
2016-06-20 10_23_08-interactive asia optiremote

**Comment by EchterAgo** [comment]
2016-06-20 10_22_27-interactive asia optiremote

**Comment by EchterAgo** [comment]
Gu.Wpf.Localization has been updated to support neutral translation in the WPF extension, so I removed the workaround I had in place for that and updated Gu.Localization to version 3.0.0

**Comment by tgjones** [comment]
This is really great, thank you!

**Pull request merged**
