### PR TITLE
Add Russian language

### PR DESCRIPTION
**Pull request by EchterAgo**
This includes and needs #225 and #226 merged

### CODE REVIEW

**Comment by EchterAgo** [comment]
This is part of https://github.com/EchterAgo/gemini/pull/1

**Comment by Kibnet** [comment]
All right

**Comment by tgjones** [comment]
Please could you rebase?

**Comment by Kibnet** [comment]
I'm unsure that I will be able to rebase.

**Comment by Kibnet** [comment]
@tgjones, Please tell me how to do it?

**Comment by EchterAgo** [comment]
Done

**Pull request merged**
