### PR TITLE
Add Korean language

### PR DESCRIPTION
**Pull request by diluculo**
Last sibling of #237

### CODE REVIEW

**Comment by tgjones** [comment]
Please could you rebase this?

**Comment by diluculo** [comment]
Done.

**Comment by tgjones** [comment]
Thank you!

**Comment by EchterAgo** [comment]
Hmmm, I don't know how but somehow this commit includes the text for AdvancedSliderCommitErrorFormat from #192 which has not been merged yet.

**Comment by diluculo** [comment]
After rebasing and resolving conflicts, I opened ResXManager and noticed the key was included. But I couldn't find it in codes, so I simply ignored it. 

I can't find it in all my local branches, but it's more reasonable to say my initial PR had it, By the way, how can I fix this? new PR removing the key? or wait until the AdvancedSlider was introduced?

**Comment by EchterAgo** [comment]
Yes, you fix it by PR removing the key, or maybe I can get the advanced slider merged soon. Maybe it was my mistake when I cleaned up your initial PR.

**Pull request merged**
