### PR TITLE
Update the Gemini.Modules.CodeCompiler and Gemini.Demo

### PR DESCRIPTION
**Pull request by gmich**
To compile with the latest Roslyn compiler in the Microsoft.CodeAnalysis.CSharp package

### CODE REVIEW

**Comment by tgjones** [comment]
This is great stuff! I had it on a mental checklist, and then forgot about it.

But I'd prefer to use the v1.0.0 (stable) package - I've avoided having Gemini depend on pre-release NuGet packages so far. Is there a reason why you need the beta version?

**Comment by gmich** [comment]
Not really, i just subconsciously added the latest package available. The API is the same, so i guess the stable version would be a better option.

**Comment by tgjones** [comment]
Do you mind creating a new PR using the v1.0.0 package? I'm happy to do it, but if you do it you get recognised as a contributor.

**Comment by tgjones** [comment]
Oops, didn't see your second commit. I think you're missing some files from that commit though.

**Comment by gmich** [comment]
Doing it now with Microsoft.CodeAnalysis.CSharp -Version 1.0.0

**Pull request closed without merging**
