### PR TITLE
Theme: Update a lot of control styles

### PR DESCRIPTION
**Pull request by EchterAgo**
This commit generally improves the dark theme and also adds better control
styles to the Button, CheckBox, ColorPicker, ComboBox, ScrollBar, Slider,
TextBox and TreeView controls. In the theme implementation the resources
got moved from ApplicationResources to MainWindowResources so that the
settings window is not affected by the theme change.

Signed-off-by: Axel Gembe axel@gembe.net

### CODE REVIEW

**Comment by EchterAgo** [comment]
Some examples

2016-06-19 11_22_55-greenshot
2016-06-19 11_23_14-greenshot
2016-06-19 11_22_01-greenshot

**Comment by EchterAgo** [comment]
And 2 custom themes I made, if there is interest I will share them

Pink ;)

2016-06-19 11_23_25-greenshot

Dark green

2016-06-19 11_23_58-greenshot

**Comment by tgjones** [comment]
Why don't you want the settings window to be affected by theme changes? I would have thought it's nice to have all the application windows follow a consistent theme.

**Comment by EchterAgo** [comment]
I would like that too, but then i need to style some more controls first. Also, Visual Studios settings window is not themed.

**Comment by tgjones** [comment]
> Also, Visual Studios settings window is not themed.

I did read somewhere that the VS team does want the settings window to be themed, they just haven't gotten to it yet.

**Comment by EchterAgo** [comment]
Removed dependency on #192

**Comment by EchterAgo** [comment]
I changed it so that the settings window should be themed now too. Also, a rebuilt version of the VS2013 theme would be needed as I made a fix there too.

**Comment by tgjones** [comment]
> Also, a rebuilt version of the VS2013 theme would be needed as I made a fix there too.

Do you want to include a new build of `AvalonDock.Themes.VS2013.dll` in the `lib` folder here in Gemini, as part of this PR?

**Comment by tgjones** [comment]
> I changed it so that the settings window should be themed now too.

Great, thank you!

**Comment by EchterAgo** [comment]
OK, I will add a rebuilt AvalonDock.Themes.VS2013.dll soon

**Comment by EchterAgo** [comment]
Library is updated now, also added a new style for TextBlock and updated the button styles slightly to better fit.

**Comment by EchterAgo** [comment]
I fixed some wrong styles, improved others and added a complete theme for the color picker

**Comment by tgjones** [comment]
Thanks for updating this. I've had a chance to try it out, and it looks great. I did notice a couple of issues though:

* Light theme - document and tool selected tab titles have the wrong text colour (it should be white, but it's black).
* Blue theme - document and tool unselected tab titles have the wrong text colour (it should be white, but it's black)
* Light and blue themes - status bar text, I think it should be white, but it's black

**Comment by EchterAgo** [comment]
I will look into it. I also noticed selected tabs can not be closed properly as the button is missing.

**Comment by EchterAgo** [comment]
Yea, I think I shouldn't style TextBlock but label instead. So far I had problems getting my Label style to work though.

**Comment by EchterAgo** [comment]
OK, everything is fixed now. The close button issue seems to have been caused by my updated VS2013 theme library. I removed it from the commit until I figure out what is wrong.

**Comment by EchterAgo** [comment]
The issue with the close button seems to be caused by this commit:
https://github.com/4ux-nbIx/AvalonDock.Themes.VS2013/commit/32ad416870526f64f038f10b6f7ac1e22bac2c67

**Comment by EchterAgo** [comment]
I fixed the issue and submitted a pull request upstream. I've also included a rebuilt version of the library in the commit. This should be able to be merged now.

**Comment by EchterAgo** [comment]
Also, I replicated the Visual Studio TreeView style, you can see it in the options window.

**Comment by EchterAgo** [comment]
Theme: Improve keyboard navigation and focus behaviour

Signed-off-by: Axel Gembe <axel@gembe.net>

**Comment by EchterAgo** [comment]
https://github.com/4ux-nbIx/AvalonDock.Themes.VS2013/pull/8 has been merged now

**Comment by diluculo** [comment]
@EchterAgo, I found this PO while finding a proper TreeView style on my project. Thanks for great work. I rebased and added ScrollViewer style. The result is [big_theme_update_EchterAgobranch](https://github.com/diluculo/gemini/tree/big_theme_update_EchterAgo).

**Comment by EchterAgo** [comment]
Rebased this on current master. Removed my rebuilt `AvalonDock.Themes.VS2013.dll`. Any issues that still prevent this from being merged?

**Comment by EchterAgo** [comment]
I also added the changes by @diluculo

**Comment by tgjones** [comment]
Thanks, looks good! Nice to see you are still using Gemini 👍

**Comment by EchterAgo** [comment]
Thanks for merging :) Yes, I'm still using Gemini, its just that some other projects and some personal issues have taken most of my time lately. I have more things that I want to contribute soon.

**Pull request merged**
