### PR TITLE
Fix for errors per appveyor build.

### PR DESCRIPTION
**Pull request by nestquik**
\*deleted\*

### CODE REVIEW

**Comment by tgjones** [comment]
@nestquik thank you for taking the time to do this. But as far as I can tell, the build errors on AppVeyor are in the XNA project, and are caused by XNA not being installed on the AppVeyor build image. Although Gemini also has a MonoGame module, adding the MonoGame DLLs to the XNA project wouldn't help in this case.

I think the correct fix is to somehow install XNA 4.0 on the AppVeyor build image, using [this redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=20914) and [these steps](https://stackoverflow.com/questions/37566019/how-do-i-install-software-which-has-a-gui-installer-on-appveyor).

**Comment by nestquik** [comment]
I can't say for sure, but after this changes AppVeyor correctly build the project as far as I can see:
https://ci.appveyor.com/project/nestquik/gemini/build/1.0.7

P.S. It is necessary to observe...

**Comment by tgjones** [comment]
Interesting - indeed it does build. But I notice a number of warnings like this, so I'm not sure that the resulting XNA module DLL is bound to the correct reference:

```
C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.Xna.Framework.Graphics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=842cf8be1de50553, processorArchitecture=x86". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\projects\gemini\src\Gemini.Demo.Xna\Gemini.Demo.Xna.csproj]
```

**Comment by tgjones** [comment]
I'm pretty sure it started failing when XNA was removed from AppVeyor's default build image. Prior to that, XNA was installed on AppVeyor's default build image.

**Comment by nestquik** [comment]
Okay, so we need to install XNA before build?
I'll look for ways to do this.

**Comment by nestquik** [comment]
Work's like a charm.
[Link to build](https://ci.appveyor.com/project/nestquik/gemini/build/1.0.16).

**Comment by tgjones** [comment]
That's great, thank you! It will be so much easier to automatically deploy new NuGet versions safely once this is fixed.

One small request though - did you copy install-XNA.ps1 from somewhere? If so, please could you credit the source at the top of the file? Then I'll merge this.

**Comment by nestquik** [comment]
> One small request though - did you copy install-XNA.ps1 from somewhere?
Yep, from [here](https://bitbucket.org/rbwhitaker/xna-beyond-vs-2010/downloads/)

**Comment by nestquik** [comment]
Done.

**Comment by tgjones** [comment]
Thank you so much, this is great.

**Comment by nestquik** [comment]
You're welcome! 😄

**Pull request merged**
